apiVersion: v2
name: spark-apps
description: Helm chart for deploying SparkApplication resources with Argo CD
type: application
version: 0.2.0
appVersion: "4.1.1"

dependencies:
  - name: spark-apps
    version: "0.1.2"
    repository: "oci://ghcr.io/datahub-local/spark-apps"
