SELECT
  CAST(NULLIF(TRIM("symboling"), '?') AS INTEGER)            AS symboling,
  CAST(NULLIF(TRIM("normalized-losses"), '?') AS INTEGER)    AS normalized_losses,
  TRIM("make")                                               AS make,
  TRIM("fuel-type")                                          AS fuel_type,
  TRIM("aspiration")                                         AS aspiration,
  TRIM("num-of-doors")                                       AS num_of_doors,
  TRIM("body-style")                                         AS body_style,
  TRIM("drive-wheels")                                       AS drive_wheels,
  TRIM("engine-location")                                    AS engine_location,
  CAST(NULLIF(TRIM("wheel-base"), '?') AS DOUBLE)           AS wheel_base,
  CAST(NULLIF(TRIM("length"), '?') AS DOUBLE)               AS length,
  CAST(NULLIF(TRIM("width"), '?') AS DOUBLE)                AS width,
  CAST(NULLIF(TRIM("height"), '?') AS DOUBLE)               AS height,
  CAST(NULLIF(TRIM("curb-weight"), '?') AS INTEGER)         AS curb_weight,
  TRIM("engine-type")                                        AS engine_type,
  TRIM("num-of-cylinders")                                   AS num_of_cylinders,
  CAST(NULLIF(TRIM("engine-size"), '?') AS INTEGER)         AS engine_size,
  TRIM("fuel-system")                                        AS fuel_system,
  CAST(NULLIF(TRIM("bore"), '?') AS DOUBLE)                 AS bore,
  CAST(NULLIF(TRIM("stroke"), '?') AS DOUBLE)               AS stroke,
  CAST(NULLIF(TRIM("compression-ratio"), '?') AS DOUBLE)   AS compression_ratio,
  CAST(NULLIF(TRIM("horsepower"), '?') AS INTEGER)         AS horsepower,
  CAST(NULLIF(TRIM("peak-rpm"), '?') AS INTEGER)           AS peak_rpm,
  CAST(NULLIF(TRIM("city-mpg"), '?') AS INTEGER)           AS city_mpg,
  CAST(NULLIF(TRIM("highway-mpg"), '?') AS INTEGER)        AS highway_mpg,
  CAST(NULLIF(TRIM("price"), '?') AS DOUBLE)               AS price,
  CURRENT_TIMESTAMP                                          AS updated_date
FROM {{ source('example_db', 'automotive_source') }}
WHERE COALESCE(TRIM("make"), '') <> ''
